"""empty message

Revision ID: 9652c82ca7af
Revises: 993cd42c6d79
Create Date: 2019-12-15 18:30:00.916789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9652c82ca7af'
down_revision = '993cd42c6d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ninjas', sa.Column('dojos_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'ninjas', type_='foreignkey')
    op.create_foreign_key(None, 'ninjas', 'dojos', ['dojos_id'], ['id'])
    op.drop_column('ninjas', 'dojo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ninjas', sa.Column('dojo_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'ninjas', type_='foreignkey')
    op.create_foreign_key(None, 'ninjas', 'dojos', ['dojo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ninjas', 'dojos_id')
    # ### end Alembic commands ###
