"""empty message

Revision ID: 993cd42c6d79
Revises: ae02eedf07f1
Create Date: 2019-12-15 18:26:08.953564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993cd42c6d79'
down_revision = 'ae02eedf07f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ninjas', sa.Column('dojos_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'ninjas', type_='foreignkey')
    op.create_foreign_key(None, 'ninjas', 'dojos', ['dojos_id'], ['id'], ondelete='cascade')
    op.drop_column('ninjas', 'dojo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ninjas', sa.Column('dojo_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'ninjas', type_='foreignkey')
    op.create_foreign_key(None, 'ninjas', 'dojos', ['dojo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ninjas', 'dojos_id')
    # ### end Alembic commands ###
